Vagrant.configure("2") do |config|
  # Машина 1: Веб-сервер с NAT для выхода в интернет
  config.vm.define "web-server" do |web|
    web.vm.box = "./bento-ubuntu-22.04"
    web.vm.network "forwarded_port", guest: 80, host: 8080 # Проброс порта для Nginx
    web.vm.network "private_network", ip: "192.168.56.10"  # Статический IP для DMZ
    web.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)" # NAT
    web.vm.hostname = "web-server"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  end

  # Машина 2: Сервер базы данных MariaDB master
  config.vm.define "db-master" do |db_master|
    db_master.vm.box = "./bento-ubuntu-22.04"
    db_master.vm.network "private_network", ip: "192.168.56.11" # Статический IP
    db_master.vm.hostname = "db-master"
    db_master.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Машина 3: Сервер базы данных MariaDB slave
  config.vm.define "db-slave" do |db_slave|
    db_slave.vm.box = "./bento-ubuntu-22.04"
    db_slave.vm.network "private_network", ip: "192.168.56.12" # Статический IP
    db_slave.vm.hostname = "db-slave"
    db_slave.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Машина 4: Мониторинг
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box = "./bento-ubuntu-22.04"
    monitoring.vm.network "private_network", ip: "192.168.56.13" # Статический IP
    monitoring.vm.hostname = "monitoring"
    monitoring.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Машина 5: Централизованный сбор логов
  config.vm.define "log-collector" do |log_collector|
    log_collector.vm.box = "./bento-ubuntu-22.04"
    log_collector.vm.network "private_network", ip: "192.168.56.14" # Статический IP
    log_collector.vm.hostname = "log-collector"
    log_collector.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 4
    end
  end

  # Машина 6: Резервное копирование
  config.vm.define "backup-server" do |backup|
    backup.vm.box = "./bento-ubuntu-22.04"
    backup.vm.network "private_network", ip: "192.168.56.15" # Статический IP
    backup.vm.hostname = "backup-server"
    backup.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end

